week2/eCommerce_Platform/config/routes.rb
Rails.application.routes.draw do
  root :to => "backpacks#welcome"
  resources :laptops
  resources :backpacks
  # en lugar de resources, se puede escribir las rutas de la siguiente forma de maner individual:
  # get "/laptops", to: "laptops#index", as "laptops"
  # get "/laptops/:id", to: "laptops#show"
  # etc....
  # si en la consola de cmd, escribimos rails routes, te muestra todas las rutas que se ha generado

end

week2/eCommerce_Platform/app/models/backpack.rb
class Backpack < ActiveRecord::Base
	
	#attr_accessible :photo, :model
	#belongs_to :backpack
	#mount_uploader :photo, ImageUploader
	


	#attr_accessible :photo, :model
	#PHOTOS = File.join Rails.root, 'app', 'assets', 'images'
	#after_save :save_photo

	#def photo=(file_data)
	#	unless file_data.blank?
	#		@file_data = file_data
	#		self.extension = file_data.original_filename.split('.').last.downcase
	#	end
	#end

	#def photo_filename
	#	File.join PHOTOS, "#{id}.#{extension}"
	#end

	#def photo_path
	#	"#{id}.#{extension}"
	#end

	#def has_photo? 
	#	File.exists? photo_filename
	#end

	#private
	#def save_photo
	#	if @file_data
	#		FileUtils.mkdir_p PHOTOS 
	#		File.open(photo_filename, 'wb') do |f| 
	#			f.write(@file_data.read)
	#		end

#			@file_data = nil
#		end

#	end


end

week2/eCommerce_Platform/app/controllers/backpacks_controller.rb
class BackpacksController < ApplicationController
	def index
		@backpacks = Backpack.all
	end

	def show
		@backpack = Backpack.find(params[:id])
	end

	def new
		@backpack = Backpack.new
	end

	def edit
		@backpack = Backpack.find(params[:id])
	end

	def create
		@backpack = Backpack.new(backpack_params)
		@backpack.save
		
		redirect_to backpack_path(@backpack)
	end

	def update
		@backpack = Backpack.find(params[:id])
		@backpack.update(backpack_params)
		redirect_to backpack_path(@backpack)
	end

	def destroy
		@backpack = Backpack.find(params[:id])
		@backpack.destroy

		redirect_to backpacks_path
	end

	def welcome
		@backpack = "backpacks"
		@laptop = "laptops"
	end

	private
	def backpack_params
		params.require(:backpack).permit( :model, :color, :capacity, :number_of_pockets, :waterproof, :price, :photo)
	end
end

week2/eCommerce_Platform/app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
	def index
		@laptops = Laptop.all #se usa @ para que se pueda interpretar tambien por viewers ademas de los controladores
		# .all es para que coja todos los laptos que hay
	end

	def show
		@laptop = Laptop.find(params[:id]) # para mostrar los distintos parametros de cada laptop
	end

	def new
		@laptop = Laptop.new
	end

	def edit
		@laptop = Laptop.find(params[:id])
	end

	def create
		@laptop = Laptop.new(laptop_params)
		@laptop.save
		redirect_to laptop_path(@laptop)
	end

	def update
		@laptop = Laptop.find(params[:id])
		@laptop.update(laptop_params)
		redirect_to  laptop_path(@laptop) #laptop_path es el metodo show al fin y al cabo
	end

	def destroy
		@laptop = Laptop.find(params[:id])
		@laptop.destroy

		redirect_to root_path
	end

	private # para aceptar solo los parametros que nos interesa o se quiere controlar
	def laptop_params
		params.require(:laptop).permit(:brand, :model, :processor_brand, :ram_size, :price)
	end
end

week2/eCommerce_Platform/app/helpers/backpacks_helper.rb
module BackpacksHelper
end

week2/eCommerce_Platform/app/views/backpacks/_form.html.erb
<%= form_for(@backpack, html: {multipart: true}) do |f| %> 
	
	<p>
		<%= f.label :photo %><br>
    	<%= f.file_field :photo %>
  	</p>

  	<p><%= f.submit %></p>
<% end %>

week2/eCommerce_Platform/app/views/backpacks/edit.html.erb
<body>
  <header>
    <h1>Editing Backpack</h1>
  </header>

  <%= form_for :backpack, html: {multipart: true}, url: backpack_path(@backpack), method: :patch do |x| %>
 
<p class="stylemarino">
    <%= x.label :model %><br>
    <%= x.text_field :model %>
  </p>

  <p class="stylemarino">
    <%= x.label :color %><br>
    <%= x.text_area :color %>
  </p>

  <p class="stylemarino">
    <%= x.label :capacity %><br>
    <%= x.text_area :capacity %>
  </p>

  <p class="stylemarino">
    <%= x.label :number_of_pockets %><br>
    <%= x.text_area :number_of_pockets %>
  </p>
  
  <p class="stylemarino">
    <%= x.label :waterproof %><br>
    <%= x.text_area :waterproof %>
  </p>

  <p class="stylemarino">
    <%= x.label :price %><br>
    <%= x.text_area :price %>
  </p>

  <p class="stylemarino">
    <%= x.label :photo %><br>
    <%= x.file_field :photo %><br>
  </p>

  <p>
    <%= x.submit %>
  </p>

  <% end %>
  <p>
    <%= link_to 'Back', backpacks_path%>
  </p>
</body>

week2/eCommerce_Platform/app/views/backpacks/index.html.erb
<body>

	<header>
		<h1> Backpacks </h1>
	</header>

	<p class="bodycenter">
		<%= image_tag("mochila1.jpg", height: "300", width: "320", align: "center") %>
		<%= image_tag("mochila3.jpg", height: "300", width: "400", align: "center") %>

		<% @backpacks.each do |backpack|%>

		<ul>
			<li>
				<div>
					<strong><%= backpack.model %> </strong><br> <br>
					<%= link_to 'Show',  backpack_path(backpack) %>
					<%= link_to 'Edit', edit_backpack_path(backpack) %>
					<%= link_to 'Destroy', backpack_path(backpack), method: :delete, data: { confirm: 'Are you sure?' } %> 
				</div>
			</li>
		</ul>

		<% end %>
	</p>

	<p class="bodycenter">
		<br>
		<%= link_to 'New Backpack', new_backpack_path %>  | 
		<%= link_to 'Back', root_path %>
	</p>

</body>

week2/eCommerce_Platform/app/views/backpacks/new.html.erb
<body class="bodycenter">

  <header>
    <h1>New Backpack</h1>
  </header>

  <%= form_for(@backpack, html: {multipart: true}) do |x| %>
  <p class="stylemarino">
    <%= x.label :model %><br>
    <%= x.text_field :model %>
  </p>

  <p class="stylemarino">
    <%= x.label :color %><br>
    <%= x.text_area :color %>
  </p>

  <p class="stylemarino">
    <%= x.label :capacity %><br>
    <%= x.text_area :capacity %>
  </p>

  <p class="stylemarino">
    <%= x.label :number_of_pockets %><br>
    <%= x.text_area :number_of_pockets %>
  </p>
  
  <p class="stylemarino">
    <%= x.label :waterproof %><br>
    <%= x.text_area :waterproof %>
  </p>

  <p class="stylemarino">
    <%= x.label :price %><br>
    <%= x.text_area :price %>
  </p>

  <p class="stylemarino">
    <%= x.label :photo %><br>
    <%= x.file_field :photo %><br>
  </p>

  <p>
    <%= x.submit %>
  </p>

  <% end %>

  <p class="style1">
    <%= link_to 'Back', backpacks_path %>
  </p>

</body>

week2/eCommerce_Platform/app/views/backpacks/show.html.erb
<body class="bodycolor">
	<h2 >
		<strong>Model:</strong>
		<%= @backpack.model %>
	</h2>

	<ul>
		<li class="styleblack">
			<strong>Color:</strong>
			<%= @backpack.color %>
		</li>

		<li class="styleblack">
			<strong>Capacity (in liters):</strong>
			<%= @backpack.capacity %>
		</li>

		<li class="styleblack">
			<strong>Number of pockets:</strong>
			<%= @backpack.number_of_pockets %>
		</li>

		<li class="styleblack">
			<strong>If it is waterproof:</strong>
			<%= @backpack.waterproof %>
		</li>

		<li class="styleblack">
			<strong>Price (€):</strong>
			<%= @backpack.price %>
		</li>
	</ul> 

	<p> 
		<%= image_tag(@backpack.photo, height: "300", width: "320", align: "center") %>
	</p>
    

	<p>
		<%= link_to 'Edit', edit_backpack_path(@backpack)%> |
    	<%= link_to 'Back', backpacks_path %>
	</p>
	
</body>

week2/eCommerce_Platform/app/views/backpacks/welcome.html.erb
<body>

	<header>
		<h1> Welcome </h1>
	</header>

	<p class="bodycenter">
		<%= image_tag("mochila2.jpg", height: "300", width: "320", align: "center") %>
		<%= image_tag("Portatil_Acer.jpg", height: "300", width: "350", align: "center") %>
	</p>

	<p class="bodycenter">
		<%= link_to "Backpacks", backpacks_path(@backpack) %>   |  
		<%= link_to "Laptops", laptops_path(@laptop) %>              
	</p>

</body>

week2/eCommerce_Platform/app/views/laptops/edit.html.erb
<body>
  <header>
    <h1>Editing Laptop</h1>
  </header>

  <%= form_for :laptop, url: laptop_path(@laptop), method: :patch do |f| %> 
  <!--@laptop y :laptop es lo mismo-->
  <!--@ method: :patch para que use el mismo metodo-->

  <p class="stylepurple">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </p>

  <p class="stylepurple">
    <%= f.label :model %><br>
    <%= f.text_area :model %>
  </p>

  <p class="stylepurple">
    <%= f.label :processor_brand %><br>
    <%= f.text_area :processor_brand %>
  </p>
  
  <p class="stylepurple">
    <%= f.label :ram_size %><br>
    <%= f.text_area :ram_size %>
  </p>

  <p class="stylepurple">
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

  <p>
    <%= link_to 'Back', laptops_path%>
  </p>
</body>

week2/eCommerce_Platform/app/views/laptops/index.html.erb
<body>

	<header>
		<h1> Laptops </h1>
	</header>

	<p class="bodycenter">
		<%= image_tag("Portatil_Toshiva.png", height: "300", width: "320", align: "center") %>
		<%= image_tag("Portatil_Apple.jpg", height: "300", width: "400", align: "center") %>

		<% @laptops.each do |laptop|%>  <!-- comentarios -->
			<ul><li><div><strong><%= laptop.brand %> </strong>
			<%= link_to 'Show',  laptop_path(laptop) %>
			<%= link_to 'Edit', edit_laptop_path(laptop) %>
			<%= link_to 'Destroy', laptop_path(laptop), method: :delete, data: { confirm: 'Are you sure?' } %>
		</div></li></ul>
		<% end %>
	</p>

	<p class="bodycenter">
		<%= link_to 'New laptop', new_laptop_path %>  | 
		<%= link_to 'Back', root_path %>
	</p>

</body>

week2/eCommerce_Platform/app/views/laptops/new.html.erb
<body class="bodycenter">

<header>
  <h1>New Laptop</h1>
</header>

  <%= form_for @laptop do |f| %>
  <p class="stylemarino">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </p>

  <p class="stylemarino">
    <%= f.label :model %><br>
    <%= f.text_area :model %>
  </p>

  <p class="stylemarino">
    <%= f.label :processor_brand %><br>
    <%= f.text_area :processor_brand %>
  </p>
  
  <p class="stylemarino">
    <%= f.label :ram_size %><br>
    <%= f.text_area :ram_size %>
  </p>

  <p class="stylemarino">
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

  <p class="style1">
    <%= link_to 'Back', laptops_path %>
  </p>

</body>

week2/eCommerce_Platform/app/views/laptops/show.html.erb
<body class="bodycolor">
	<h2 >
		<strong>Brand:</strong>
		<%= @laptop.brand %>
	</h2>

	<ul>
		<li class="styleblack">
			<strong>Model:</strong>
			<%= @laptop.model %>
		</li>

		<li class="styleblack">
			<strong>Processor Brand:</strong>
			<%= @laptop.processor_brand %>
		</li>

		<li class="styleblack">
			<strong>RAM:</strong>
			<%= @laptop.ram_size %>
		</li>

		<li class="styleblack">
			<strong>Price (€):</strong>
			<%= @laptop.price %>
		</li>
	</ul> 
	
	<p class="styleblack">
		<%= link_to 'Edit', edit_laptop_path(@laptop)%> |
    	<%= link_to 'Back', laptops_path%>
	</p>
	
</body>